### ISSUE TITLE
after server start running:  uirecorder ini --mobile

### ISSUE THREAD

**Issue by syberkitten** [macacajs/macaca-adb#25]
returns this error from server:
```
Error: >> helper.js:112:12 [master] pid:6706 please set ANDROID_HOME
      at Logger.error (/usr/local/lib/node_modules/macaca-android/node_modules/xlogger/lib/xlogger.js:169:9)
      at Object._.getAdbPath (/usr/local/lib/node_modules/macaca-android/node_modules/macaca-adb/lib/helper.js:112:12)
      at Object._.adbShell (/usr/local/lib/node_modules/macaca-android/node_modules/macaca-adb/lib/helper.js:102:21)
      at ADB.forward (/usr/local/lib/node_modules/macaca-android/node_modules/macaca-adb/lib/macaca-adb.js:143:15)
      at UIAutomator.init (/usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/lib/uiautomator-client.js:25:18)
      at UIAutomator.init.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by syberkitten** [comment]
setting ANDROID_HOME helped to resolve this issue.
